services:
  - type: web
    name: coxist-backend
    env: node
    plan: free
    buildCommand: cd server && pnpm install && pnpm run build
    startCommand: cd server && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
